spring:
  profiles:
    active: dev

---

spring:
  datasource:
    url: ${site_db_url}
    username: ${site_db_username}
    password: ${site_db_password}
  servlet:
    multipart:
      max-request-size: 16MB
      max-file-size: 16MB
  mvc:
    static-path-pattern: /static/**
  jpa:
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: dev
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

server:
  port: ${PORT}
  servlet:
    session:
      timeout: 180m

api-token:
  crc32-secret-key: 6n3X891gMO@L8vHte$0X02d@#&KHChJl

---

spring:
  datasource:
    url: ${SITE_DB_URL}
    username: ${SITE_DB_USERNAME}
    password: ${SITE_DB_PASSWORD}
  servlet:
    multipart:
      max-request-size: 8MB
      max-file-size: 8MB
  mvc:
    static-path-pattern: /static/**
  jpa:
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: prod
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

server:
  port: ${SITE_PORT}
  servlet:
    session:
      timeout: 180m

api-token:
  crc32-secret-key: 8PMqx^izdWVWnWk3%2oyP5d5Yo2oWhJu